// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store.DAL;

#nullable disable

namespace Store.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260607164257_editColumnDate")]
    partial class editColumnDate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Store.DAL.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Computer Peripherals"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Furniture & Setup"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Smart Home & Lifestyle"
                        });
                });

            modelBuilder.Entity("Store.DAL.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpriryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Count = 12,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wireless RGB with tactile switches.",
                            Price = 85.00m,
                            Title = "Mechanical Keyboard"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Count = 8,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-speed external storage for developers.",
                            Price = 115.00m,
                            Title = "Portable SSD 1TB"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Count = 40,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "7-in-1 connectivity for modern laptops.",
                            Price = 35.00m,
                            Title = "USB-C Hub Adapter"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Count = 25,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Reduces wrist strain during long coding sessions.",
                            Price = 29.99m,
                            Title = "Vertical Mouse"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Count = 10,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Active noise cancellation for focused work.",
                            Price = 199.00m,
                            Title = "Noise Cancelling Headphones"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 1,
                            Count = 6,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Wide-angle lens with built-in dual microphones.",
                            Price = 89.90m,
                            Title = "Webcam 4K Ultra HD"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Count = 5,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "High-back mesh chair with lumbar support.",
                            Price = 210.50m,
                            Title = "Ergonomic Office Chair"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Count = 15,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Heavy-duty aluminum arm for two 27-inch screens.",
                            Price = 65.25m,
                            Title = "Dual Monitor Stand"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Count = 50,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Large felt mat for mouse and keyboard stability.",
                            Price = 18.50m,
                            Title = "Desk Pad Protector"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Count = 20,
                            CreatedAt = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Self-watering kit with LED grow lights for mint and basil.",
                            Price = 45.99m,
                            Title = "Smart Indoor Herb Garden"
                        });
                });

            modelBuilder.Entity("Store.DAL.Product", b =>
                {
                    b.HasOne("Store.DAL.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Store.DAL.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
